//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASVideosPublicationAssistant.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TASVideosPublicationAssistant.Resources.MockData", typeof(MockData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;success&quot;: true,
        ///  &quot;values&quot;: {
        ///    &quot;cookies&quot;: {
        ///      &quot;logged-in-sig&quot;: &quot;fC9yfSyQn3VugJ164eAe2l7o2EaRVnbXQPjz4cYYfVu4Hz5CFj8fl1BtTAbMbQtndxElU2SKVfvK15QfOVEnGqHh5hA7E3YQzKMbGriDgD0TArMvaRpe4JIhQ3HQAc1a4Cuoi56ftL9Ue6dePcKxSQPhJ3H3f46Co1eKCX1lecTemEYgWV8mKoSxwbqvQhZHRepWUaDtk8RZcjWbKJmdBbpAt3KddKF3Wt3GJdEigw9U4dJW; expires=Mon, 07-Nov-2022 01:58:15 GMT; Max-Age=31536000; path=/; domain=.archive.org&quot;,
        ///      &quot;logged-in-user&quot;: &quot;email%40gmail.com; expires=Mon, 07-Nov-2022 01:58:15 GMT; Max-Age=31536000; p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoginResponse {
            get {
                return ResourceManager.GetString("LoginResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://archive.org/metadata/gameboycamera-tas-thunderaxe31_casualpokeplayer/files.
        /// </summary>
        internal static string MetadataFiles0Query {
            get {
                return ResourceManager.GetString("MetadataFiles0Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;result&quot;:[{&quot;name&quot;:&quot;__ia_thumb.jpg&quot;,&quot;source&quot;:&quot;original&quot;,&quot;mtime&quot;:&quot;1633979694&quot;,&quot;size&quot;:&quot;16214&quot;,&quot;md5&quot;:&quot;a2b18e99e9d0412cb24af00711ff4592&quot;,&quot;crc32&quot;:&quot;71592238&quot;,&quot;sha1&quot;:&quot;0b0ef5ff60f0c027f69e1e5cba13adc2a1b3f076&quot;,&quot;format&quot;:&quot;Item Tile&quot;,&quot;rotation&quot;:&quot;0&quot;},{&quot;name&quot;:&quot;gameboycamera-tas-thunderaxe31_casualpokeplayer.mkv&quot;,&quot;source&quot;:&quot;original&quot;,&quot;mtime&quot;:&quot;1633979099&quot;,&quot;size&quot;:&quot;6120678&quot;,&quot;md5&quot;:&quot;b8b2897319233388f0a2d3fa012a21e4&quot;,&quot;crc32&quot;:&quot;65d3b989&quot;,&quot;sha1&quot;:&quot;f3683d4f49b63737689c4d3f2207df5cf32f3c3c&quot;,&quot;format&quot;:&quot;Matroska&quot;,&quot;length&quot;:&quot;429.71&quot;,&quot;heig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetadataFiles0Response {
            get {
                return ResourceManager.GetString("MetadataFiles0Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://archive.org/metadata/mysticalninjastarringgoemon-tas-zggzdydp/files.
        /// </summary>
        internal static string MetadataFiles1Query {
            get {
                return ResourceManager.GetString("MetadataFiles1Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;result&quot;:[{&quot;name&quot;:&quot;__ia_thumb.jpg&quot;,&quot;source&quot;:&quot;original&quot;,&quot;mtime&quot;:&quot;1633567440&quot;,&quot;size&quot;:&quot;10801&quot;,&quot;md5&quot;:&quot;30364d3b7bad969f259cc2f109a303ec&quot;,&quot;crc32&quot;:&quot;15327215&quot;,&quot;sha1&quot;:&quot;aa0e48648374e5ada43c64fd34f68b672535c3db&quot;,&quot;format&quot;:&quot;Item Tile&quot;,&quot;rotation&quot;:&quot;0&quot;},{&quot;name&quot;:&quot;mysticalninjastarringgoemon-tas-zggzdydp.mkv&quot;,&quot;source&quot;:&quot;original&quot;,&quot;mtime&quot;:&quot;1633545952&quot;,&quot;size&quot;:&quot;395591025&quot;,&quot;md5&quot;:&quot;c95793a195c8ed713af48c66fa1a5cae&quot;,&quot;crc32&quot;:&quot;aa077992&quot;,&quot;sha1&quot;:&quot;85ff8d7afe427af31f211fbea10c485ce896a62c&quot;,&quot;format&quot;:&quot;Matroska&quot;,&quot;length&quot;:&quot;8087.02&quot;,&quot;height&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetadataFiles1Response {
            get {
                return ResourceManager.GetString("MetadataFiles1Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://archive.org/metadata/spiderman-gc-tasv2-natetheman223/files.
        /// </summary>
        internal static string MetadataFiles2Query {
            get {
                return ResourceManager.GetString("MetadataFiles2Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;result&quot;:[{&quot;name&quot;:&quot;__ia_thumb.jpg&quot;,&quot;source&quot;:&quot;original&quot;,&quot;mtime&quot;:&quot;1632440294&quot;,&quot;size&quot;:&quot;10545&quot;,&quot;md5&quot;:&quot;cca3ae25ba163adff90f68bba6589fec&quot;,&quot;crc32&quot;:&quot;d31f0923&quot;,&quot;sha1&quot;:&quot;2d725b5820c5ede9d2bfeebb99c27b531f1f129f&quot;,&quot;format&quot;:&quot;Item Tile&quot;,&quot;rotation&quot;:&quot;0&quot;},{&quot;name&quot;:&quot;spiderman-gc-tasv2-natetheman223.mkv&quot;,&quot;source&quot;:&quot;original&quot;,&quot;mtime&quot;:&quot;1631859711&quot;,&quot;size&quot;:&quot;818659606&quot;,&quot;md5&quot;:&quot;dc1068502920aa4a4a67596210fb0469&quot;,&quot;crc32&quot;:&quot;2929901c&quot;,&quot;sha1&quot;:&quot;021d768150dc07f0d6e94df9e2acfcfdb893d36c&quot;,&quot;format&quot;:&quot;Matroska&quot;,&quot;length&quot;:&quot;3514.74&quot;,&quot;height&quot;:&quot;448&quot;,&quot;w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetadataFiles2Response {
            get {
                return ResourceManager.GetString("MetadataFiles2Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://archive.org/metadata/ssbb-tasv2-subspaceemissary_1player-dyllonstej/files.
        /// </summary>
        internal static string MetadataFiles3Query {
            get {
                return ResourceManager.GetString("MetadataFiles3Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;result&quot;:[{&quot;name&quot;:&quot;__ia_thumb.jpg&quot;,&quot;source&quot;:&quot;original&quot;,&quot;mtime&quot;:&quot;1630428243&quot;,&quot;size&quot;:&quot;11507&quot;,&quot;md5&quot;:&quot;0bfc43f98aa91897a704c8911816518f&quot;,&quot;crc32&quot;:&quot;213aa612&quot;,&quot;sha1&quot;:&quot;8262534f6be08a2a6e359d91109031c27606bcba&quot;,&quot;format&quot;:&quot;Item Tile&quot;,&quot;rotation&quot;:&quot;0&quot;},{&quot;name&quot;:&quot;ssbb-tasv2-subspaceemissary_1player-dyllonstej.mkv&quot;,&quot;source&quot;:&quot;original&quot;,&quot;mtime&quot;:&quot;1630422642&quot;,&quot;size&quot;:&quot;1329279640&quot;,&quot;md5&quot;:&quot;4181aeeb369c99d74f26a99bfe5b017e&quot;,&quot;crc32&quot;:&quot;41ae952b&quot;,&quot;sha1&quot;:&quot;2fef87d8c1a1652953537a68f4905d0d86cf70e1&quot;,&quot;format&quot;:&quot;Matroska&quot;,&quot;length&quot;:&quot;4113.02&quot;,&quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetadataFiles3Response {
            get {
                return ResourceManager.GetString("MetadataFiles3Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://archive.org/metadata/dk64-tas-nolevelsearly-theballaam96/files.
        /// </summary>
        internal static string MetadataFiles4Query {
            get {
                return ResourceManager.GetString("MetadataFiles4Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This won&apos;t be parsed correctly..
        /// </summary>
        internal static string MetadataFiles4Response {
            get {
                return ResourceManager.GetString("MetadataFiles4Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tasvideos.org/1234S.html.
        /// </summary>
        internal static string SubmissionQuery {
            get {
                return ResourceManager.GetString("SubmissionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tasvideos.org/1007S.html.
        /// </summary>
        internal static string SubmissionQueryFail {
            get {
                return ResourceManager.GetString("SubmissionQueryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1 plus MathML 2.0//EN&quot; &quot;http://www.w3.org/Math/DTD/mathml2/xhtml-math11-f.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:g=&quot;http://base.google.com/ns/1.0&quot; xmlns:addthis=&quot;http://www.addthis.com/help/api-spec&quot; xml:lang=&quot;en&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;TASVideos submissions: #7240: duuuuude5&apos;s Linux Undertale v1.001 &amp;quot;Minimum Z/Enter Presses - Neutral Ending&amp;quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubmissionResponse {
            get {
                return ResourceManager.GetString("SubmissionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This won&apos;t be parsed correctly..
        /// </summary>
        internal static string SubmissionResponseFail {
            get {
                return ResourceManager.GetString("SubmissionResponseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;responseHeader&quot;:{&quot;status&quot;:0,&quot;QTime&quot;:9,&quot;params&quot;:{&quot;query&quot;:&quot;( uploader:email@gmail.com )&quot;,&quot;qin&quot;:&quot;uploader:email@gmail.com&quot;,&quot;fields&quot;:&quot;identifier,name,title&quot;,&quot;wt&quot;:&quot;json&quot;,&quot;sort&quot;:&quot;addeddate desc&quot;,&quot;rows&quot;:&quot;5&quot;,&quot;start&quot;:0}},&quot;response&quot;:{&quot;numFound&quot;:92,&quot;start&quot;:0,&quot;docs&quot;:[{&quot;identifier&quot;:&quot;gameboycamera-tas-thunderaxe31_casualpokeplayer&quot;,&quot;title&quot;:&quot;gameboycamera-tas-thunderaxe31_casualpokeplayer&quot;},{&quot;identifier&quot;:&quot;mysticalninjastarringgoemon-tas-zggzdydp&quot;,&quot;title&quot;:&quot;mysticalninjastarringgoemon-tas-zggzdydp&quot;},{&quot;identifier&quot;:&quot;spiderm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserQueryResponse {
            get {
                return ResourceManager.GetString("UserQueryResponse", resourceCulture);
            }
        }
    }
}
